<?
$PERM["search"]["12"]="W";
$PERM["products"]["12"]="W";
$PERM["services"]["12"]="W";
$PERM["news"]["12"]="W";
$PERM["contacts"]["12"]="W";
$PERM["company"]["12"]="W";
$PERM["index.php"]["12"]="W";
$PERM["/"]["*"]="R";
?>